# Generated by Django 2.0.5 on 2018-07-16 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180713_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='body',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 16, 16, 45, 10, 508724)),
        ),
    ]
