# Generated by Django 3.2.11 on 2022-02-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220210_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'ordering': ('-created_time',), 'verbose_name': '博客栏目'},
        ),
        migrations.RenameField(
            model_name='articlecolumn',
            old_name='create_time',
            new_name='created_time',
        ),
    ]
