# Generated by Django 3.2.11 on 2022-02-11 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_time',), 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
    ]
